xKV_config:
  # Model configuration
  num_layers: 32  # Adjust based on your model
  
  # Compression method: "svd" or "slerp"
  layer_merge_impl: "svd"
  
  # SVD compression parameters
  rank_k: 256      # Rank for key compression
  rank_v: 768      # Rank for value compression
  
  # SLERP parameters (used when layer_merge_impl is "slerp")
  slerp_t: 0.5     # Interpolation ratio
  slerp_gamma: 0.05 # Gamma for divergent token identification
  
  # What to compress
  merge_key: true
  merge_value: true
  
  # Layer groups for compression
  # Each group specifies which layers to merge together
  layer_groups:
    # Group 1: Layers 0-1
    - layers: [0, 1]
      rank_k: 256
      rank_v: 768
    
    # Group 2: Layers 2-3  
    - layers: [2, 3]
      rank_k: 256
      rank_v: 768
    
    # Group 3: Layers 4-5
    - layers: [4, 5]
      rank_k: 256
      rank_v: 768
    
    # Group 4: Layers 6-7
    - layers: [6, 7]
      rank_k: 256
      rank_v: 768
    
    # Group 5: Layers 8-9
    - layers: [8, 9]
      rank_k: 256
      rank_v: 768
    
    # Group 6: Layers 10-11
    - layers: [10, 11]
      rank_k: 256
      rank_v: 768
    
    # Group 7: Layers 12-13
    - layers: [12, 13]
      rank_k: 256
      rank_v: 768
    
    # Group 8: Layers 14-15
    - layers: [14, 15]
      rank_k: 256
      rank_v: 768
    
    # Group 9: Layers 16-17
    - layers: [16, 17]
      rank_k: 256
      rank_v: 768
    
    # Group 10: Layers 18-19
    - layers: [18, 19]
      rank_k: 256
      rank_v: 768
    
    # Group 11: Layers 20-21
    - layers: [20, 21]
      rank_k: 256
      rank_v: 768
    
    # Group 12: Layers 22-23
    - layers: [22, 23]
      rank_k: 256
      rank_v: 768
    
    # Group 13: Layers 24-25
    - layers: [24, 25]
      rank_k: 256
      rank_v: 768
    
    # Group 14: Layers 26-27
    - layers: [26, 27]
      rank_k: 256
      rank_v: 768
    
    # Group 15: Layers 28-29
    - layers: [28, 29]
      rank_k: 256
      rank_v: 768
    
    # Group 16: Layers 30-31
    - layers: [30, 31]
      rank_k: 256
      rank_v: 768 