xKV_config:
  num_layers: 32
  layer_merge_impl: svd
  rank_k: 512
  rank_v: 768
  slerp_t: 0.5
  slerp_gamma: 0.05
  merge_key: true
  merge_value: true
  layer_groups:
  - layers:
    - 0
    - 1
    - 2
    - 3
    rank_k: 512
    rank_v: 768
  - layers:
    - 4
    - 5
    - 6
    - 7
    rank_k: 512
    rank_v: 768
  - layers:
    - 8
    - 9
    - 10
    - 11
    rank_k: 512
    rank_v: 768
  - layers:
    - 12
    - 13
    - 14
    - 15
    rank_k: 512
    rank_v: 768
  - layers:
    - 16
    - 17
    - 18
    - 19
    rank_k: 512
    rank_v: 768
  - layers:
    - 20
    - 21
    - 22
    - 23
    rank_k: 512
    rank_v: 768
  - layers:
    - 24
    - 25
    - 26
    - 27
    rank_k: 512
    rank_v: 768
  - layers:
    - 28
    - 29
    - 30
    - 31
    rank_k: 512
    rank_v: 768
